version: "3.9"

services:
  frontend:
    build: .
    container_name: woodwarehouse
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./app:/app  # Sinkronisasi kode lokal dengan container
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge