services:
  frontend:
    build: .
    container_name: woodwarehouse-frontend
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge