name: CI/CD for Streamlit App

on:
  push:
    branches:
      - jovan
  pull_request:
    branches:
      - jovan

jobs:
  test-and-deploy:
    runs-on: ubuntu-22.04  # Gunakan Ubuntu 22.04 untuk Python 3.10

    steps:
    # Step 1: Checkout kode dari repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libjpeg-dev zlib1g-dev libfreetype6-dev liblcms2-dev libopenjp2-7-dev libtiff5-dev tk-dev tcl-dev

    # Step 3: Setup Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Tanpa sub-version untuk kompatibilitas

    # Step 4: Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Run tests
    - name: Run tests
      run: |
        pytest tests/

    # Step 6: Linting
    - name: Run linter
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  