name: CI/CD for Streamlit App

on:
  push:
    branches:
      - main  # Jalankan workflow setiap kali ada push ke branch `main`
  pull_request:
    branches:
      - main  # Jalankan workflow untuk pull request ke branch `main`

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout kode dari repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install system dependencies (untuk Pillow)
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libjpeg-dev zlib1g-dev libfreetype6-dev liblcms2-dev libopenjp2-7-dev libtiff5-dev tk-dev tcl-dev

    # Step 3: Setup Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.7

    # Step 4: Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Run tests
    - name: Run tests
      run: |
        pytest tests/

    # Step 6: Linting (Opsional)
    - name: Run linter
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics